env:
  browser: true
  es6: true
  node: true
  worker: true
  jquery: true
  serviceworker: true

rules:
  strict: [2, global]
  comma-dangle: [2, always-multiline]
  comma-style: [2, last]
  array-bracket-spacing: [2, never]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  no-mixed-spaces-and-tabs: 2
  one-var: [2, never]
  object-curly-spacing: [2, never]
  quotes: [2, single, avoid-escape]
  semi: [2, always]
  space-after-keywords: [2, always]
  space-before-blocks: [2, always]
  space-before-function-paren: [2, {anonymous: always, named: never}]
  space-in-parens: [2, never] # exceptions?
  space-return-throw-case: 2
  spaced-comment: [2, always]

  # es6
  arrow-spacing: 2
  no-const-assign: 2
  prefer-const: 2
  object-shorthand: [2, methods]
